import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { TaskDetail, TaskView } from '../../work-intake/types';
import * as resourceApi from '../../workspace/resourceApi';
import * as workIntakeApi from '../../work-intake/api';
import { LiveUploadPanel } from './LiveUploadPanel';

vi.mock('../../workspace/resourceApi', () => ({
  uploadResource: vi.fn(),
  readResourceText: vi.fn()
}));

vi.mock('../../work-intake/api', async () => {
  const actual = await vi.importActual<typeof import('../../work-intake/api')>(
    '../../work-intake/api'
  );
  return {
    ...actual,
    submitQuery: vi.fn(),
    getTask: vi.fn(),
    approvePlan: vi.fn()
  };
});

const plannedDetail = {
  task: { task_id: 'task-1', status: 'AWAITING_PLAN_APPROVAL' },
  run: null,
  plan: {
    plan_version: 1,
    query_template_hash: 'sha256:plan',
    approval_mode: 'REQUIRE_INTERACTIVE',
    steps: [
      { assigned_module: 'module_2', capability_id: 'documents.analyze.v1' },
      { assigned_module: 'module_3', capability_id: 'artifact.create.v1' }
    ]
  },
  steps: [],
  step_results: []
} as unknown as TaskDetail;

const completedDetail = {
  ...plannedDetail,
  task: { task_id: 'task-1', status: 'COMPLETED' },
  final_response: {
    artifact_refs: [
      {
        ref_id: 'staged-report',
        checksum: 'sha256:report'
      }
    ]
  }
} as unknown as TaskDetail;

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe('LiveUploadPanel', () => {
  it('uploads through the broker, requires approval, and reads the final artifact ref', async () => {
    vi.mocked(resourceApi.uploadResource).mockResolvedValue({
      ref_id: 'source-sales',
      checksum: 'sha256:source',
      media_type: 'text/markdown',
      size_bytes: 100
    });
    vi.mocked(workIntakeApi.submitQuery).mockResolvedValue({
      task_id: 'task-1',
      status: 'AWAITING_PLAN_APPROVAL'
    } as TaskView);
    vi.mocked(workIntakeApi.getTask)
      .mockResolvedValueOnce(plannedDetail)
      .mockResolvedValueOnce(completedDetail);
    vi.mocked(workIntakeApi.approvePlan).mockResolvedValue(plannedDetail.plan!);
    vi.mocked(resourceApi.readResourceText).mockResolvedValue(
      '# Immutable report\n\nGenerated by Module 3.'
    );

    render(<LiveUploadPanel />);
    fireEvent.click(screen.getByRole('button', { name: /general document\/data analysis/i }));
    fireEvent.change(screen.getByLabelText(/file cho preset/i), {
      target: {
        files: [
          new File(['# Sales'], 'sales.md', {
            type: 'text/markdown'
          })
        ]
      }
    });
    fireEvent.click(screen.getByRole('button', { name: /tạo kế hoạch/i }));

    await screen.findByRole('button', { name: /phê duyệt/i });
    expect(resourceApi.uploadResource).toHaveBeenCalledTimes(1);
    expect(workIntakeApi.submitQuery).toHaveBeenCalledWith(
      expect.objectContaining({
        attachmentRefs: [expect.objectContaining({ ref_id: 'source-sales' })]
      })
    );

    fireEvent.click(screen.getByRole('button', { name: /phê duyệt/i }));

    await waitFor(() =>
      expect(resourceApi.readResourceText).toHaveBeenCalledWith(
        'staged-report',
        expect.objectContaining({ actorId: 'demo-user' })
      )
    );
    expect(await screen.findByText(/immutable report/i)).toBeTruthy();
  });

  it('renders a terminal workflow error instead of a sample artifact', async () => {
    vi.mocked(resourceApi.uploadResource).mockResolvedValue({
      ref_id: 'source-sales',
      checksum: 'sha256:source',
      media_type: 'text/markdown',
      size_bytes: 100
    });
    vi.mocked(workIntakeApi.submitQuery).mockResolvedValue({
      task_id: 'task-1',
      status: 'RUNNING'
    } as TaskView);
    vi.mocked(workIntakeApi.getTask)
      .mockResolvedValueOnce({
        ...plannedDetail,
        task: { task_id: 'task-1', status: 'RUNNING' }
      } as unknown as TaskDetail)
      .mockResolvedValueOnce({
        ...completedDetail,
        task: { task_id: 'task-1', status: 'FAILED' },
        final_response: {
          artifact_refs: [],
          error: { user_message: 'Module 3 storage failed.' }
        }
      } as unknown as TaskDetail);

    render(<LiveUploadPanel />);
    fireEvent.click(screen.getByRole('button', { name: /general document\/data analysis/i }));
    fireEvent.change(screen.getByLabelText(/file cho preset/i), {
      target: { files: [new File(['# Sales'], 'sales.md')] }
    });
    fireEvent.click(screen.getByRole('button', { name: /tạo kế hoạch/i }));

    expect((await screen.findByRole('alert')).textContent).toContain(
      'Module 3 storage failed.'
    );
    expect(resourceApi.readResourceText).not.toHaveBeenCalled();
    expect(screen.queryByText(/immutable report/i)).toBeNull();
  });
});
