"""Framework-free V2-M1 contracts for chat and the Memory Gateway boundary."""

from ._chat_contracts_chat import (
    ChatMessageRequest,
    ChatMessageStreamEvent,
    stream_event_from_dict,
)
from ._chat_contracts_common import (
    AI_CHAT_FEATURE,
    CHAT_CONTRACTS_VERSION,
    MAX_CHAT_MESSAGE_LENGTH,
    MAX_CHAT_SUMMARY_LENGTH,
    MAX_EPISODIC_RETRIEVAL_ITEMS,
    MAX_RETRIEVAL_QUERY_LENGTH,
    MAX_RETRIEVAL_TIMEOUT_MS,
    MAX_SEMANTIC_RETRIEVAL_ITEMS,
    ChatEventType,
    ChatToolChoice,
    DegradedMemorySource,
    EpisodeSourceType,
    MemoryCitationType,
    MemoryType,
)
from ._chat_contracts_memory import (
    PROFILE_PREFERENCE_FIELDS,
    ChatMemoryScope,
    ChatSummaryEpisode,
    ChatTurn,
    DeclarativeProfile,
    EpisodeCitation,
    EpisodeTransition,
    EpisodicMemoryQuery,
    EpisodicMemoryRead,
    MemoryContextRequest,
    MemoryContextResponse,
    MemoryNamespace,
    MemoryProvenance,
    MemoryProvenanceSource,
    MemoryReadOptions,
    SemanticMemoryQuery,
    SemanticMemoryRead,
    TaskEpisode,
)
from .target_contracts import ValidationStatus

__all__ = [
    "AI_CHAT_FEATURE",
    "CHAT_CONTRACTS_VERSION",
    "MAX_CHAT_MESSAGE_LENGTH",
    "MAX_EPISODIC_RETRIEVAL_ITEMS",
    "MAX_RETRIEVAL_QUERY_LENGTH",
    "MAX_RETRIEVAL_TIMEOUT_MS",
    "MAX_SEMANTIC_RETRIEVAL_ITEMS",
    "PROFILE_PREFERENCE_FIELDS",
    "ChatEventType",
    "ChatMemoryScope",
    "ChatSummaryEpisode",
    "ChatMessageRequest",
    "ChatMessageStreamEvent",
    "ChatToolChoice",
    "ChatTurn",
    "DeclarativeProfile",
    "DegradedMemorySource",
    "EpisodeCitation",
    "EpisodeSourceType",
    "EpisodeTransition",
    "EpisodicMemoryRead",
    "EpisodicMemoryQuery",
    "MemoryCitationType",
    "MAX_CHAT_SUMMARY_LENGTH",
    "MemoryContextRequest",
    "MemoryContextResponse",
    "MemoryNamespace",
    "MemoryProvenance",
    "MemoryProvenanceSource",
    "MemoryReadOptions",
    "MemoryType",
    "SemanticMemoryRead",
    "SemanticMemoryQuery",
    "TaskEpisode",
    "ValidationStatus",
    "stream_event_from_dict",
]
